Release v1.6 – Major Restructure, Remove Reflections API, Cooldowns & `jda5.0.0-alpha.23`
DynxstyGIT/DIH4JDA pull request #39
Opened 2022-07-05 15:25 UTC by DynxstyGIT

# Changes

- [X] #40 by @DenuxPlays
- [X] #44 by @DenuxPlays 
- [X] #45 by @DenuxPlays 
- [X] #42 by @DenuxPlays 
- [x] #53 by @DenuxPlays 
- [x] #57
- [x] Add Listener-support for new Select Menu Types
- [x] Added independent Component Interfaces by @DynxstyGIT 
- [x] #64 by @DynxstyGIT 
- [x] #55
- [x] Update ReadMe
- [x] Fix old Javadocs 
- [x] #60 
- [x] #62
- [x] #65
- [x] add package-info.java(s)
- [ ] add examples #74 
- [ ] Update JDA to `5.0.0-alpha.23`
<br>

- [ ] change version from alpha to stable

2022-07-21 13:10 UTC, DenuxPlays reviewed
Dude then actually review pr's before you merge them... idiot

2022-08-05 22:50 UTC, MoonTM-GIT commented
Before this gets merged I'd like to look through all the javadoc and improve it where necessary if that's alright

2022-11-09 22:55 UTC, DenuxPlays commented
@DynxstyGIT review please

2022-11-10 11:36 UTC, DenuxPlays requested changes
Fix the broken package pls

2022-11-10 14:08 UTC, DenuxPlays approved these changes

2022-11-10 14:09 UTC, DynxstyGIT commented
no wont merge.

2022-11-10 14:19 UTC, DenuxPlays commented
> no wont merge.

stfu you did nothing for like the past 2 months or more

2022-11-11 13:38 UTC, DenuxPlays requested changes
Still hate wilcard imports

2022-11-11 13:38 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/events/ThrowableDIH4JDAEvent.java
> +	public Throwable getThrowable() {
```suggestion
@NonNull
	public Throwable getThrowable() {
```

2022-11-11 13:41 UTC, DenuxPlays commented
And are we waiting for #62 to be merged or not?

2022-11-11 13:41 UTC, DynxstyGIT commented
yessir

2022-11-11 13:43 UTC, DenuxPlays commented
Ok then get this ready.
Goal is to merge this as soon as jda alpha.23 releases!

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 */
```suggestion
	/**
	 * Disables stacktrace-printing for all raised exceptions that were not catched by an {@link DIH4JDAEventListener}.
	 *
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
	 */
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 * @return the {@link DIH4JDABuilder} instance. Usefully for chaining methods.
```suggestion
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 * @return the {@link DIH4JDABuilder} instance. Usefully for chaining methods.
```suggestion
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 * @return the {@link DIH4JDABuilder} instance. Usefully for chaining methods.
```suggestion
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 */
```suggestion
	/**
	 * Disables the deletion of unknown/unused commands while using SmartQueue.
	 *
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
	 */
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 * @return the {@link DIH4JDABuilder} instance. Usefully for chaining methods.
```suggestion
	 * @return The {@link DIH4JDABuilder} for chaining convenience.
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDABuilder.java
> +	 */
```suggestion
	/**
	 * Returns a validated {@link DIH4JDA} instance.
	 *
	 * @return The built, usable {@link DIH4JDA}
	 * @throws DIH4JDAException if anything was wrong with your configuration.
	 */
```

2022-11-13 22:07 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDA.java
> + */
```suggestion
/**
 * <p><b>Getting Started</b></p>
 *
 * Creating a new DIH4JDA instance is fairly easy:
 *
 * <pre>{@code
 * DIH4JDA dih4jda = DIH4JDABuilder
 *         .setJDA(jda) // Your JDA instance
 *         .build();
 * }</pre>
 *
 * Now, you get to decide how you want your commands to be registered:
 *
 * <p><b>Manual Command Registration</b></p>
 *
 * To manually register commands, use the following methods, <b>AFTER</b> you've <code>.build();</code> your DIH4JDA instance, like that:
 *
 * <pre>{@code
 * DIH4JDA dih4jda = DIH4JDABuilder
 *         .setJDA(jda) // Your JDA instance
 *         .build();
 * dih4jda.addSlashCommands(new PingCommand(), new HelloWorldCommand());
 * dih4jda.addContextMenus(new PingUserContext(), new HelloWorldMessageContext());
 * }</pre>
 *
 * <p><b>Automatic Command Registration</b></p>
 *
 * Alternatively, you can specify packages on the {@link DIH4JDABuilder} instance which will be scanned for all classes that extend one of the following classes:
 *
 * <ul>
 *     <li>{@link SlashCommand}</li>
 *     <li>{@link ContextCommand.User}</li>
 *     <li>{@link ContextCommand.Message}</li>
 * </ul>
 *
 * <pre>{@code
 * DIH4JDA dih4jda = DIH4JDABuilder
 *         .setJDA(jda) // Your JDA instance
 *         .setCommandPackages("xyz.dynxsty.bot.commands") // OPTIONAL: The package(s) that contains all your commands
 *         .build();
 * }</pre>
 *
 * Upon calling <code>.build();</code>, the bot will register all commands that are in the specified package(s).
 */
```

2022-11-14 07:10 UTC, DenuxPlays requested changes

2022-11-14 07:10 UTC, DenuxPlays commented on .github/workflows/gradle.yml
> +    branches: [ "dev" ]
```suggestion
    branches: [ dev ]
```

2022-11-14 07:10 UTC, DenuxPlays commented on build.gradle.kts
> +if (getProjectProperty("manualCI") != null) {
```suggestion
/*
Add the manualCI property to your gralde.properties
Sets failOnError on the javadocJar tasks to your specified boolean.
*/
if (getProjectProperty("manualCI") != null) {
```

2022-11-14 07:10 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/DIH4JDALogger.java
> +//TODO java docs
TODO

2022-11-14 07:10 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
> +	private void checkUnknown(String prefix, @Nonnull final List<Command> existing, Command command) {
Can we please add javadocs here for general understanding

2022-11-14 07:10 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
> +	private void checkRequiredGuilds(Guild guild, Command cmd, @Nonnull BaseApplicationCommand<?, ? extends CommandData> app) {
Javadocs here too please

2022-11-14 07:10 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/events/CommandCooldownEvent.java
> + * <h2>Command Cooldowns DO NOT persist between sessions!</h2>
```suggestion
 * <b>Command Cooldowns DO NOT persist between sessions!</b>
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Constructs a new {@link InteractionHandler} from the supplied {@link DIH4JDA} instance}.
	 *
	 * @param dih4jda The {@link DIH4JDA} instance.
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Uses the provided {@link Set} of {@link SlashCommandData} and {@link CommandData ContextCommandData} 
	 * and queues them globally, using the {@link JDA} instance.
	 *
	 * @param jda             The {@link JDA} instance.
	 * @param slashCommand    A {@link Set} of {@link SlashCommandData}.
	 * @param contextCommands A {@link Set} of {@link CommandData},
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Uses the provided {@link Set} of {@link SlashCommandData} and {@link CommandData ContextCommandData} 
	 * and queues them, using the specified {@link Guild} instance.
	 * This also checks for {@link BaseApplicationCommand#getQueueableGuilds queueable guilds} and skips them if needed.
	 *
	 * @param guild           The {@link Guild}.
	 * @param slashCommands   A {@link Set} of {@link SlashCommandData}.
	 * @param contextCommands A {@link Set} of {@link CommandData},
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Searches for {@link SlashCommand}s or {@link SlashCommand.Subcommand}s which implement the {@link AutoCompletable} interface.
	 *
	 * @param command The base {@link SlashCommand}.
	 * @param clazz   The command's class.
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Gets the complete {@link SlashCommandData} (including Subcommands & Subcommand Groups) from a single {@link SlashCommand}.
	 *
	 * @param command      The base command's instance.
	 * @param commandClass The base command's class.
	 * @return The new {@link CommandListUpdateAction}.
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	 */
```suggestion
	/**
	 * Gets all {@link SubcommandGroupData} (including Subcommands) from a single {@link SlashCommand}.
	 *
	 * @param command The base command's instance.
	 * @return All {@link SubcommandGroupData} stored in a List.
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
> + * "new" (commands, which yet do not exist) or edited commands , which reduces the amount of total command updates.
```suggestion
 * "new" (commands, which yet do not exist) or edited commands, which reduces the amount of total command updates.
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
> +	 */
```suggestion
	/**
	 * Compares the specified {@link CommandData} with already existing Commands, removes duplicates and, if enabled, deletes unknown commands.
	 *
	 * @return A {@link Pair} with the remaining {@link SlashCommandData} and {@link CommandData}.
	 * @since v1.5
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/SmartQueue.java
> +	 */
```suggestion
	/**
	 * Compares the specified {@link CommandData} with already existing Commands, removes duplicates and, if enabled, deletes unknown commands.
	 *
	 * @param guild The {@link Guild} which is used to retrieve the already existing commands.
	 * @return A {@link Pair} with the remaining {@link SlashCommandData} and {@link CommandData}.
	 * @since v1.5
	 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/config/DIH4JDAConfig.java
> + */
```suggestion
/**
 * Simple data class which represents {@link DIH4JDA}'s configuration.
 */
```

2022-11-14 10:29 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/config/DIH4JDAConfig.java
> +    //We have to find a better name for this boolean
```suggestion
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/exceptions/DIH4JDAException.java
> + */
```suggestion
/**
 * The top-level {@link Exception} that is thrown for everything regarding DIH4JDA.
 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/interactions/commands/ExecutableCommand.java
> + */
```suggestion
/**
 * Represents an executable command.
 * @param <E> The corresponding event.
 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
> +	 */
```suggestion
	/**
	 * Returns an array of all {@link Subcommand}s this command contains.
	 *
	 * @return An {@link Subcommand}-array.
	 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
> +	 */
```suggestion
	/**
	 * Adds {@link Subcommand}s to this {@link SlashCommand}. 
	 *
	 * @param classes Instances of the {@link Subcommand}s to add.
	 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
> +	 */
```suggestion
	/**
	 * Returns an array of all {@link SubcommandGroups}s this command contains.
	 *
	 * @return An {@link SubcommandGroup}-array.
	 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/interactions/commands/application/SlashCommand.java
> +	 */
```suggestion
	/**
	 * Adds {@link SubcommandGroups}s to this {@link SlashCommand}.
	 *
	 * @param groups Instances of the {@link SubcommandGroup} class.
	 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/util/ArrayUtil.java
> + */
```suggestion
/**
 * Utility class that contains some useful methods regarding arrays.
 *
 * @since v1.6
 */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/util/ArrayUtil.java
> +     */
```suggestion
    /**
     * Checks if the specified object is inside the specifed array.
     *
     * @param array The array to check.
     * @param search The {@link Object} to search for.
     * @return Whether the object is contained inside the array.
     */
```

2022-11-14 11:35 UTC, DynxstyGIT commented on src/main/java/xyz/dynxsty/dih4jda/util/IOUtils.java
> + */
```suggestion
/**
 * Utility class that contains some useful methods regarding IO.
 *
 * @since v1.6
 */
```

2022-11-14 11:36 UTC, DynxstyGIT commented
Despite some docs I ignored for now as they're likely to change in the future, everything looks good so far.

2022-11-14 11:53 UTC, DenuxPlays commented on src/main/java/xyz/dynxsty/dih4jda/InteractionHandler.java
> +	protected final Set<ContextCommand<?>> contextCommands;
because its getting used in DIH4JDA

2022-11-14 16:45 UTC, DenuxPlays approved these changes

2022-11-14 16:47 UTC, merged