Overloaded CommandRequirements#requireUsers and CommandRequirements#requireRoles
DynxstyGIT/DIH4JDA pull request #48
Opened 2022-08-05 21:01 UTC by DenuxPlays

CommandRequirements#requireUsers and CommandRequirements#requireRoles accepts now collections of ids.

2022-08-05 21:07 UTC, MoonTM-GIT requested changes

2022-08-05 21:07 UTC, MoonTM-GIT commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/CommandRequirements.java
> +	 * Allows to require a set of {@link Long}s (user Ids) which are able to execute the corresponding command.
```suggestion
	 * Defines a set of User-IDs as {@link Long}s which are able to execute the corresponding command.
```
That could confuse some people as it sounds like all roles would be required to execute the corresponding command. Besides that, it doesn't allow to do something - it does it. When you use that method it's not optional to "allow" these users

2022-08-05 21:07 UTC, MoonTM-GIT commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/CommandRequirements.java
> +	 * Allows to require a set of {@link Long}s (role Ids) which are able to execute the corresponding command.
```suggestion
	 * Defines a set of Role-IDs as {@link Long}s which are able to execute the corresponding command.
```
That could confuse some people as it sounds like all roles would be required to execute the corresponding command. Besides that, it doesn't allow to do something - it does it. When you use that method it's not optional to "allow" these roles

2022-08-05 21:12 UTC, MoonTM-GIT commented
I know these are basically just copied over but I'd suggest changing where you got these from as well

2022-08-05 21:15 UTC, DenuxPlays commented
> I know these are basically just copied over but I'd suggest changing the documentation where you got that from as well

What you mean with `where you got that from`?

2022-08-05 21:17 UTC, DynxstyGIT requested changes

2022-08-05 21:17 UTC, DynxstyGIT commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/BaseCommandRequirements.java
> +	}
Just parse the Collection to an Array and call the "original" method instead of implementing the logic twice.

2022-08-05 21:17 UTC, MoonTM-GIT commented
Well, you basically copied that from some other method - just change it there to what I requested as well

Or if you don't want to I can probably go look through some more stuff and make a pr myself

2022-08-05 21:18 UTC, DynxstyGIT commented
Same applies for all other overloads you just made. Just use the original method. I don't know what you're up to, but I generally try to avoid code duplication

2022-08-05 21:19 UTC, DenuxPlays commented
> Same applies for all other overloads you just made. Just use the original method. I don't know what you're up to, but I generally try to avoid code duplication

Some may have a list with required Users or something like that I just dont like the idea of only providing this method without overloading it but you can just close the pr you dont what this

2022-08-05 21:20 UTC, MoonTM-GIT commented
You didn't understand what he wants, you're supposed to just parse the collection to an array and then **call the original method in your overload** instead of copying the code.

2022-08-05 21:20 UTC, DynxstyGIT commented
> > Same applies for all other overloads you just made. Just use the original method. I don't know what you're up to, but I generally try to avoid code duplication
> 
> 
> 
> Some may have a list with required Users or something like that I just dont like the idea of only providing this method without overloading it but you can just close the pr you dont what this 

What? No. I'm fine with having method overloads. Just don't implement the whole logic twice and just use the original methods.

2022-08-05 21:21 UTC, DenuxPlays commented
> > > Same applies for all other overloads you just made. Just use the original method. I don't know what you're up to, but I generally try to avoid code duplication
> > 
> > 
> > Some may have a list with required Users or something like that I just dont like the idea of only providing this method without overloading it but you can just close the pr you dont what this
> 
> What? No. I'm fine with having method overloads. Just don't implement the whole logic twice and just use the original methods.

Oh yeah okay thougth you disliked the idea of overloading.
The thing with the duplicated logic was my bad sorry fixed that already

2022-08-05 22:44 UTC, MoonTM-GIT requested changes

2022-08-05 22:44 UTC, MoonTM-GIT commented on src/main/java/com/dynxsty/dih4jda/DIH4JDA.java
> +	 * Defines a set of objects that implements {@link DIH4JDAEventListener} to be registered as an event listener.
```suggestion
	 * Defines a set of objects that implement {@link DIH4JDAEventListener} to be registered as an event listener.
```

2022-08-05 22:44 UTC, MoonTM-GIT commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/CommandRequirements.java
> +	 * Allows to require a set of {@link Permission}s which are needed to execute the corresponding command.
```suggestion
	 * Defines a set of {@link Permission}s that are required to execute the corresponding command.
```

2022-08-05 22:47 UTC, MoonTM-GIT approved these changes

2022-08-05 23:45 UTC, DynxstyGIT commented
Tbh, I don't see a reason why anyone would want to use a collection for those methods:

> DIH4JDABuilder#disableLogging -> Collections<DIH4JDALogger.Type> types
> DIH4JDABuilder#setCommandPackages -> Collections packages
> 
> DIH4JDA#addEventListener -> Collection classes
> DIH4JDA#addSlashCommands -> Collection commands
> DIH4JDA#addContextCommands -> Collection(ContextCommand) commands

2022-08-05 23:58 UTC, DenuxPlays commented
> Tbh, I don't see a reason why anyone would want to use a collection for those methods:
> 
> > DIH4JDABuilder#disableLogging -> Collections<DIH4JDALogger.Type> types
> > DIH4JDABuilder#setCommandPackages -> Collections packages
> > DIH4JDA#addEventListener -> Collection classes
> > DIH4JDA#addSlashCommands -> Collection commands
> > DIH4JDA#addContextCommands -> Collection(ContextCommand) commands

may be there have a list (out of a config or something) for required users, guilds... and they dont want to put toArray... every time

2022-08-05 23:59 UTC, DynxstyGIT commented
Yeah. If you could read, you'd see that I didn't mention ALL methods. 🤡

2022-08-06 00:00 UTC, DenuxPlays commented
> Yeah. If you could read, you'd see that I didn't mention ALL methods. 🤡

right sorry yeah I wasn't sure about these methods maybe its useless maybe not

2022-09-13 16:37 UTC, DenuxPlays commented
Irrelevant due to: #50

2022-09-13 16:37 UTC, closed without merging