Fixed bug in CommandRequirements and BasicCommandRequirements
DynxstyGIT/DIH4JDA pull request #49
Opened 2022-08-05 22:37 UTC by DenuxPlays

If the methods in those two classes would be given null as an argument.

2022-08-05 22:38 UTC, DenuxPlays commented on src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
> +				}
I am not quite sure if we should continue the loop or not

2022-08-05 22:41 UTC, MoonTM-GIT approved these changes

2022-08-05 23:40 UTC, DynxstyGIT commented
Please improve the wording of the Exception Messages, so it doesn't sound like a first-grader wrote them.

2022-08-05 23:42 UTC, DenuxPlays commented
> Please improve the wording of the Exception Messages, so it doesn't sound like a first-grader wrote them.

GitHub Copilot wrote them lmao

2022-08-05 23:43 UTC, DynxstyGIT requested changes

2022-08-05 23:43 UTC, DynxstyGIT commented on src/main/java/com/dynxsty/dih4jda/InteractionHandler.java
> +				}
And what the flip is this?? Just do 
```suggestion
				String message = e.getMessage() == null ? e.getCause().getMessage() : e.getMessage();
```

2022-08-05 23:44 UTC, DynxstyGIT commented
And what even is the actual fix? Throwing an exception with the arrays are null?

2022-08-05 23:45 UTC, DenuxPlays commented
> And what even is the actual fix? Throwing an exception when the arrays are null?

better than your error message that was "null"

2022-08-05 23:47 UTC, DynxstyGIT commented
What??

2022-08-05 23:48 UTC, DenuxPlays commented
> What??

![image](https://user-images.githubusercontent.com/83671398/183224394-be668876-b0f3-48cf-8d57-6dd4a19178ca.png)
Your error message

2022-08-05 23:48 UTC, DynxstyGIT requested changes

2022-08-05 23:48 UTC, DynxstyGIT commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/BaseCommandRequirements.java
>  		}
Check first for the type, then if the array is null

2022-08-05 23:49 UTC, DynxstyGIT commented
> > What??
> 
> ![image](https://user-images.githubusercontent.com/83671398/183224394-be668876-b0f3-48cf-8d57-6dd4a19178ca.png) Your error message

Bro thats the default NPE message...

2022-08-05 23:49 UTC, DenuxPlays commented
> > > What??
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/83671398/183224394-be668876-b0f3-48cf-8d57-6dd4a19178ca.png) Your error message
> 
> Bro thats the default NPE message...

but still nobody know what the hell is wrong

2022-08-05 23:50 UTC, DenuxPlays commented on src/main/java/com/dynxsty/dih4jda/interactions/commands/BaseCommandRequirements.java
>  		}
but why? if the array is null you dont have to check for the type

2022-09-13 16:37 UTC, DenuxPlays commented
Irrelevant due to: #50

2022-09-13 16:37 UTC, closed without merging